---
# file: tasks/configuration.yml
#
# configuration tasks.
#

- name: "configuration | ensure integrity of {{ defaults_directory }}/{{ bind_service }} file"
  template:
    src=etc/default/bind9.j2
    dest="{{ defaults_directory }}/{{ bind_service }}"
    owner=root
    group=root
    mode=0644
  notify: restart bind

- name: "configuration | ensure integrity of {{ named_path }}/named.conf file"
  template:
    src="etc/bind/named.conf{{ item }}.j2"
    dest="{{ named_path }}/named.conf{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - ''
  notify: restart bind

- name: "configuration | ensure integrity of {{ named_configs_path }}/named.conf.* files"
  template:
    src="etc/bind/named.conf{{ item }}.j2"
    dest="{{ named_configs_path }}/named.conf{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - '.acl'
    - '.controls'
    - '.keys'
    - '.local'
    - '.logging'
    - '.options'
  notify: restart bind

- name: configuration | generate custom zone databases
  template:
    src=var/cache/bind/db.name.zone.j2
    dest="{{ bind_dir_cache }}/db.{{ item.key }}.zone"
    owner="{{ bind_user }}"
    group="{{ bind_user }}"
    mode=0644
  with_dict: "{{ bind_zone_databases }}"
  notify: restart bind

