---
# file: tasks/installation.yml
#
# installation tasks.
#

- name: installation | install packages
  package:
    name="{{ item }}"
    state=present
  with_items:
    - "{{ packages }}"

- name: installation | ensure log directory is present
  file:
    path="{{ bind_dir_log }}"
    state=directory
    owner="{{ bind_user }}"
    group="{{ bind_user }}"
    mode=0755
