---
# file: bind/tasks/main.yml
#
# tasks file
#

- include_vars: "vars/{{ ansible_distribution }}.yml"

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: installation.yml
  tags: installation
  sudo: yes

- include: configuration.yml
  tags: configuration
  sudo: yes

- include: apparmor.yml
  tags: apparmor
  sudo: yes
  when:
    - '"Ubuntu" in ansible_distribution'
