---
# file: bind/handlers/main.yml
#
# handlers file
#

- name: "reload {{ bind_service }}"
  service:
    name="{{ bind_service }}"
    state=reloaded
  sudo: yes

- name: "restart {{ bind_service }}"
  service:
    name="{{ bind_service }}"
    state=restarted
  sudo: yes

- name: "start {{ bind_service }}"
  service:
    name="{{ bind_service }}"
    state=started
  sudo: yes

- name: "stop {{ bind_service }}"
  service:
    name="{{ bind_service }}"
    state=stopped
  sudo: yes
